[testRace1] ant -f  C:/AppData/Setup/calfuzzer/calfuzzer2.0/calfuzzer2/calfuzzer/run.xml test_race1
[testRace3] ant -f  C:/AppData/Setup/calfuzzer/calfuzzer2.0/calfuzzer2/calfuzzer/run.xml test_race2
[CASE3] ant -f  C:/AppData/Setup/calfuzzer/calfuzzer2.0/calfuzzer2/calfuzzer/run.xml test_race3
[CASE4] ant -f  C:/AppData/Setup/calfuzzer/calfuzzer2.0/calfuzzer2/calfuzzer/run.xml test_race4
[CASE5] ant -f  C:/AppData/Setup/calfuzzer/calfuzzer2.0/calfuzzer2/calfuzzer/run.xml test_race5
[CASE6] ant -f  C:/AppData/Setup/calfuzzer/calfuzzer2.0/calfuzzer2/calfuzzer/run.xml test_race6
[CASE7] ant -f  C:/AppData/Setup/calfuzzer/calfuzzer2.0/calfuzzer2/calfuzzer/run.xml test_race7
[CASE8] ant -f  C:/AppData/Setup/calfuzzer/calfuzzer2.0/calfuzzer2/calfuzzer/run.xml test_race8
[CASE9] ant -f  C:/AppData/Setup/calfuzzer/calfuzzer2.0/calfuzzer2/calfuzzer/run.xml test_race9
[CASE10] ant -f  C:/AppData/Setup/calfuzzer/calfuzzer2.0/calfuzzer2/calfuzzer/run.xml test_race10
[CASE11] ant -f  C:/AppData/Setup/calfuzzer/calfuzzer2.0/calfuzzer2/calfuzzer/run.xml test_race11